import { RequiredDataFromCollectionSlug } from 'payload'

export const contactForm: RequiredDataFromCollectionSlug<'forms'> = {
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Signal received.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h3',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you. Your message has been logged. I\u2019ll review it within 24 hours and respond directly to your email.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          textStyle: '',
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  confirmationType: 'message',
  createdAt: '2023-01-12T21:47:41.374Z',
  emails: [
    {
      emailFrom: '"Payload" \u003Cdemo@payloadcms.com\u003E',
      emailTo: '{{email}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Your contact form submission was successfully received.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              textStyle: '',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      subject: "You've received a new message.",
    },
  ],
  fields: [
    {
      name: 'name',
      blockName: 'name',
      blockType: 'text',
      label: 'Name',
      required: true,
      width: 50,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email',
      required: true,
      width: 50,
    },
    {
      name: 'company',
      blockName: 'company',
      blockType: 'text',
      label: 'Company / Organization',
      required: false,
      width: 100,
    },
    {
      name: 'project-type',
      blockName: 'project-type',
      blockType: 'select',
      label: 'Project Type',
      required: true,
      width: 100,
      options: [
        { label: 'Full-Stack Development', value: 'full-stack-development' },
        { label: 'AI / ML Engineering', value: 'ai-ml-engineering' },
        { label: 'Technical Architecture & Consulting', value: 'technical-architecture' },
        { label: 'Frontend Engineering', value: 'frontend-engineering' },
        { label: 'Something Else', value: 'something-else' },
      ],
    },
    {
      name: 'budget',
      blockName: 'budget',
      blockType: 'select',
      label: 'Budget Range',
      required: false,
      width: 50,
      options: [
        { label: 'Under $5K', value: 'under-5k' },
        { label: '$5K — $15K', value: '5k-15k' },
        { label: '$15K — $50K', value: '15k-50k' },
        { label: '$50K+', value: '50k-plus' },
        { label: 'Let\u2019s discuss', value: 'lets-discuss' },
      ],
    },
    {
      name: 'timeline',
      blockName: 'timeline',
      blockType: 'select',
      label: 'Timeline',
      required: false,
      width: 50,
      options: [
        { label: 'ASAP', value: 'asap' },
        { label: '1—3 months', value: '1-3-months' },
        { label: '3—6 months', value: '3-6-months' },
        { label: '6+ months', value: '6-plus-months' },
        { label: 'Flexible', value: 'flexible' },
      ],
    },
    {
      name: 'message',
      blockName: 'message',
      blockType: 'textarea',
      label: 'Message',
      required: true,
      width: 100,
    },
  ],
  redirect: undefined,
  submitButtonLabel: 'SEND_MESSAGE',
  title: 'Contact Form',
  updatedAt: '2023-01-12T21:47:41.374Z',
}