import {
  IconApiApp,
  IconAutomation,
  IconBolt,
  IconBrain,
  IconBrandStripe,
  IconChartBar,
  IconChartLine,
  IconCloud,
  IconCloudComputing,
  IconCode,
  IconCoins,
  IconCreditCard,
  IconDatabase,
  IconKey,
  IconLayersIntersect,
  IconLock,
  IconNetwork,
  IconPuzzle,
  IconReceipt,
  IconRobot,
  IconRobotFace,
  IconRocket,
  IconServer,
  IconShield,
  IconShieldCheck,
  IconShieldLock,
  IconStack2,
  IconTerminal2,
  IconTestPipe,
  IconWallet,
  IconWebhook,
  IconWorld,
} from '@tabler/icons-react'
import type { ElementType } from 'react'

export const serviceIconMap: Record<string, ElementType> = {
  api: IconApiApp,
  apiapp: IconApiApp,
  automation: IconAutomation,
  bolt: IconBolt,
  brain: IconBrain,
  brandstripe: IconBrandStripe,
  chartbar: IconChartBar,
  chartline: IconChartLine,
  cloud: IconCloud,
  cloudcomputing: IconCloudComputing,
  code: IconCode,
  coins: IconCoins,
  creditcard: IconCreditCard,
  database: IconDatabase,
  key: IconKey,
  layers: IconLayersIntersect,
  lock: IconLock,
  network: IconNetwork,
  puzzle: IconPuzzle,
  receipt: IconReceipt,
  robot: IconRobot,
  robotface: IconRobotFace,
  rocket: IconRocket,
  server: IconServer,
  shield: IconShield,
  shieldcheck: IconShieldCheck,
  shieldlock: IconShieldLock,
  stack: IconStack2,
  stripe: IconBrandStripe,
  terminal: IconTerminal2,
  testpipe: IconTestPipe,
  wallet: IconWallet,
  webhook: IconWebhook,
  world: IconWorld,
}
