/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_F30819D6".
 */
export type LexicalNodes_F30819D6 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_F30819D6>
  | SerializedHorizontalRuleNode
  | SerializedAutoLinkNode<LexicalNodes_F30819D6, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_F30819D6, LexicalLinkFields>;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_F1434086".
 */
export type LexicalNodes_F1434086 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_F1434086>
  | SerializedHorizontalRuleNode
  | SerializedHeadingNode<LexicalNodes_F1434086, 'h2' | 'h3' | 'h4'>
  | SerializedAutoLinkNode<LexicalNodes_F1434086, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_F1434086, LexicalLinkFields>;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_106E6C8F".
 */
export type LexicalNodes_106E6C8F =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_106E6C8F>
  | SerializedHeadingNode<LexicalNodes_106E6C8F, 'h1' | 'h2' | 'h3' | 'h4'>
  | SerializedAutoLinkNode<LexicalNodes_106E6C8F, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_106E6C8F, LexicalLinkFields>;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_D0F9AE76".
 */
export type LexicalNodes_D0F9AE76 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_D0F9AE76>
  | SerializedHeadingNode<LexicalNodes_D0F9AE76, 'h2' | 'h3' | 'h4'>
  | SerializedAutoLinkNode<LexicalNodes_D0F9AE76, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_D0F9AE76, LexicalLinkFields>;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_744BEF80".
 */
export type LexicalNodes_744BEF80 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_744BEF80>
  | SerializedAutoLinkNode<LexicalNodes_744BEF80, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_744BEF80, LexicalLinkFields>;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_D377A99B".
 */
export type LexicalNodes_D377A99B =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_D377A99B>
  | SerializedHorizontalRuleNode
  | SerializedListNode<LexicalNodes_D377A99B>
  | SerializedListItemNode<LexicalNodes_D377A99B>
  | SerializedBlockNode<BannerBlock | CodeBlock | MediaBlock_D6C44817>
  | SerializedHeadingNode<LexicalNodes_D377A99B, 'h1' | 'h2' | 'h3' | 'h4'>
  | SerializedAutoLinkNode<LexicalNodes_D377A99B, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_D377A99B, LexicalLinkFields>;

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    folders: Folder;
    pages: Page;
    insights: Insight;
    projects: Project;
    services: Service;
    industries: Industry;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    leads: Lead;
    comments: Comment;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    folders: FoldersSelect<false> | FoldersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    about: About;
    home: Home;
    resume: Resume;
    uses: Use;
    now: Now;
    speaking: Speaking;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    resume: ResumeSelect<false> | ResumeSelect<true>;
    uses: UsesSelect<false> | UsesSelect<true>;
    now: NowSelect<false> | NowSelect<true>;
    speaking: SpeakingSelect<false> | SpeakingSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders".
 */
export interface Folder {
  id: number;
  _h_folders?: (number | null) | Folder;
  name: string;
  updatedAt: string;
  createdAt: string;
  _h_slugPath?: string | null;
  _h_titlePath?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: LexicalRichText<LexicalNodes_106E6C8F> | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'insights';
                  value: number | Insight;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: LexicalRichText<LexicalNodes_D377A99B>;
  relatedPosts?: (number | Insight)[] | null;
  categories?: (number | Category)[] | null;
  /**
   * Used to build the tag cloud in the Insights sidebar.
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  topic?: ('AI/ML' | 'Backend' | 'Frontend' | 'Architecture' | 'Career') | null;
  /**
   * e.g. "6 min read"
   */
  readTime?: string | null;
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  _h_folders?: (number | null) | Folder;
  caption?: LexicalRichText<LexicalNodes_744BEF80> | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: LexicalRichText<LexicalNodes_106E6C8F> | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'insights';
                value: number | Insight;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: LexicalRichText<LexicalNodes_D0F9AE76> | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'insights';
                value: number | Insight;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: LexicalRichText<LexicalNodes_106E6C8F> | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'insights' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'insights';
        value: number | Insight;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: LexicalRichText<LexicalNodes_106E6C8F> | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?: (Checkbox | Country | Email | Message | Number | Select | State | Text | Textarea)[] | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: LexicalRichText<LexicalNodes_106E6C8F>;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: LexicalRichText<LexicalNodes_744BEF80> | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Checkbox".
 */
export interface Checkbox {
  name: string;
  label?: string | null;
  width?: number | null;
  required?: boolean | null;
  defaultValue?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'checkbox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Country".
 */
export interface Country {
  name: string;
  label?: string | null;
  width?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'country';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Email".
 */
export interface Email {
  name: string;
  label?: string | null;
  width?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'email';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Message".
 */
export interface Message {
  message?: LexicalRichText<LexicalNodes_744BEF80> | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'message';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Number".
 */
export interface Number {
  name: string;
  label?: string | null;
  width?: number | null;
  defaultValue?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'number';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Select".
 */
export interface Select {
  name: string;
  label?: string | null;
  width?: number | null;
  defaultValue?: string | null;
  placeholder?: string | null;
  options?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'select';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "State".
 */
export interface State {
  name: string;
  label?: string | null;
  width?: number | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'state';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Text".
 */
export interface Text {
  name: string;
  label?: string | null;
  width?: number | null;
  defaultValue?: string | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Textarea".
 */
export interface Textarea {
  name: string;
  label?: string | null;
  width?: number | null;
  defaultValue?: string | null;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textarea';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  tagline?: string | null;
  description?: string | null;
  thumbnail?: (number | null) | Media;
  stack?:
    | {
        tech?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?: {
    loc?: number | null;
    commits?: number | null;
    contributors?: number | null;
  };
  liveUrl?: string | null;
  github?: string | null;
  /**
   * The problem this project solved. Rendered in a "The problem" section on the project page.
   */
  challenge?: string | null;
  /**
   * The approach taken. Rendered in a "The approach" section on the project page.
   */
  solution?: string | null;
  /**
   * Key architectural decisions, shown as an "Under the hood" grid.
   */
  architecture?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * One representative code sample shown alongside the architecture section.
   */
  codeSample?: {
    /**
     * e.g. "PaymentPipeline.php"
     */
    title?: string | null;
    language?: ('typescript' | 'javascript' | 'php' | 'python' | 'sql' | 'go' | 'bash' | 'json' | 'yaml') | null;
    code?: string | null;
  };
  /**
   * Shipped features, shown as a checklist under "What was built".
   */
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Outcome metrics shown under "The outcome" (e.g. "99.97%" / "Uptime").
   */
  resultMetrics?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lessons learned, shown under "The outcome".
   */
  lessons?:
    | {
        lesson?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Build phases, shown as a vertical timeline ("How it unfolded").
   */
  developmentTimeline?:
    | {
        /**
         * e.g. "Month 1" or "Week 1–2"
         */
        period?: string | null;
        phase?: string | null;
        description?: string | null;
        /**
         * Optional — a specific obstacle hit during this phase.
         */
        hurdle?: string | null;
        /**
         * Optional — a specific milestone hit during this phase.
         */
        milestone?: string | null;
        id?: string | null;
      }[]
    | null;
  projectStatus?: ('COMPLETED' | 'IN_PROGRESS') | null;
  category?: string | null;
  industry?: (number | null) | Industry;
  year?: number | null;
  featured?: boolean | null;
  /**
   * Lower values appear first.
   */
  sortOrder?: number | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  tagline?: string | null;
  description?: LexicalRichText<LexicalNodes_F1434086> | null;
  projectCount?: number | null;
  services?:
    | {
        service?: string | null;
        id?: string | null;
      }[]
    | null;
  keyProjects?:
    | {
        project?: string | null;
        id?: string | null;
      }[]
    | null;
  challenges?:
    | {
        challenge?: string | null;
        id?: string | null;
      }[]
    | null;
  solutions?:
    | {
        solution?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Lower values appear first.
   */
  sortOrder?: number | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Display number, e.g. "01".
   */
  num?: string | null;
  /**
   * Icon name used by the frontend, e.g. "Code2".
   */
  icon?: string | null;
  tagline?: string | null;
  description?: LexicalRichText<LexicalNodes_F1434086> | null;
  deliverables?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  stack?:
    | {
        tech?: string | null;
        id?: string | null;
      }[]
    | null;
  timeline?: string | null;
  startingFrom?: string | null;
  /**
   * Steps the client goes through when engaging this service.
   */
  process?:
    | {
        num?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional code sample shown on the service detail page.
   */
  code?: {
    language?: string | null;
    title?: string | null;
    code?: string | null;
  };
  /**
   * Engagement models.
   */
  pricing?:
    | {
        name?: string | null;
        description?: string | null;
        best?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * Used as the URL path segment for this case study.
   */
  slug: string;
  category?: string | null;
  client?: string | null;
  industry?: string | null;
  /**
   * Related project.
   */
  projectSlug?: (number | null) | Project;
  whyItMatters?: string | null;
  initialSituation?: string | null;
  scope?: string | null;
  keyDecision?: string | null;
  outcome?: string | null;
  systemsAffected?: string | null;
  metrics?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Lower values appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  author: string;
  role?: string | null;
  company?: string | null;
  quote: string;
  avatar?: (number | null) | Media;
  /**
   * Featured testimonials appear in the homepage section.
   */
  featured?: boolean | null;
  /**
   * Lower values appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Inquiries captured by the site's chat widget and contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  message: string;
  /**
   * The type of project or engagement, if stated.
   */
  projectType?: string | null;
  source?: ('chat' | 'contact-form' | 'other') | null;
  status?: ('new' | 'contacted' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  insight: number | Insight;
  author: string;
  email: string;
  content: string;
  /**
   * Only approved comments are shown publicly on the insight page.
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'insights';
          value: number | Insight;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'insights';
    value: number | Insight;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?: ('inline' | 'schedulePublish') | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processingUntil?: string | null;
  processingToken?: string | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'folders';
        value: number | Folder;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders_select".
 */
export interface FoldersSelect<T extends boolean = true> {
  _h_folders?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  _h_slugPath?: T;
  _h_titlePath?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  topic?: T;
  readTime?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  thumbnail?: T;
  stack?:
    | T
    | {
        tech?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        loc?: T;
        commits?: T;
        contributors?: T;
      };
  liveUrl?: T;
  github?: T;
  challenge?: T;
  solution?: T;
  architecture?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  codeSample?:
    | T
    | {
        title?: T;
        language?: T;
        code?: T;
      };
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  resultMetrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  lessons?:
    | T
    | {
        lesson?: T;
        id?: T;
      };
  developmentTimeline?:
    | T
    | {
        period?: T;
        phase?: T;
        description?: T;
        hurdle?: T;
        milestone?: T;
        id?: T;
      };
  projectStatus?: T;
  category?: T;
  industry?: T;
  year?: T;
  featured?: T;
  sortOrder?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  num?: T;
  icon?: T;
  tagline?: T;
  description?: T;
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  stack?:
    | T
    | {
        tech?: T;
        id?: T;
      };
  timeline?: T;
  startingFrom?: T;
  process?:
    | T
    | {
        num?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  code?:
    | T
    | {
        language?: T;
        title?: T;
        code?: T;
      };
  pricing?:
    | T
    | {
        name?: T;
        description?: T;
        best?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  projectCount?: T;
  services?:
    | T
    | {
        service?: T;
        id?: T;
      };
  keyProjects?:
    | T
    | {
        project?: T;
        id?: T;
      };
  challenges?:
    | T
    | {
        challenge?: T;
        id?: T;
      };
  solutions?:
    | T
    | {
        solution?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  sortOrder?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  slug?: T;
  category?: T;
  client?: T;
  industry?: T;
  projectSlug?: T;
  whyItMatters?: T;
  initialSituation?: T;
  scope?: T;
  keyDecision?: T;
  outcome?: T;
  systemsAffected?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  role?: T;
  company?: T;
  quote?: T;
  avatar?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  projectType?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  insight?: T;
  author?: T;
  email?: T;
  content?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _h_folders?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  meta?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processingUntil?: T;
  processingToken?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'insights';
                value: number | Insight;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'insights';
                value: number | Insight;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Display name, e.g. "Martins Michael".
   */
  name: string;
  /**
   * Hero roles, e.g. "Full-Stack Developer" and "AI Architect".
   */
  roles?:
    | {
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  tagline?: string | null;
  availability?: string | null;
  location?: string | null;
  email?: string | null;
  calendlyUrl?: string | null;
  socials?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Large homepage headline.
   */
  heroHeadline?: string | null;
  heroIntro?: LexicalRichText<LexicalNodes_F30819D6> | null;
  /**
   * Homepage metrics bar.
   */
  metrics?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Trusted-by client logos.
   */
  clients?:
    | {
        name?: string | null;
        type?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    title?: string | null;
    subtitle?: string | null;
    primaryLabel?: string | null;
    primaryTo?: string | null;
    secondaryLabel?: string | null;
    secondaryTo?: string | null;
  };
  contactIntro?: LexicalRichText<LexicalNodes_F30819D6> | null;
  contactChannels?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  projectTypes?:
    | {
        type?: string | null;
        id?: string | null;
      }[]
    | null;
  budgetRanges?:
    | {
        range?: string | null;
        id?: string | null;
      }[]
    | null;
  timelines?:
    | {
        timeline?: string | null;
        id?: string | null;
      }[]
    | null;
  contactSteps?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  contactFaq?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  footerNote?: string | null;
  footerLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'insights';
                value: number | Insight;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  layout?:
    | (
        | AboutHeroBlock
        | OriginStoryBlock
        | PhilosophyBlock
        | TimelineBlock
        | SkillsBlock
        | BeyondCodeBlock
        | CertificationsBlock
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHeroBlock".
 */
export interface AboutHeroBlock {
  portrait?: (number | null) | Media;
  /**
   * About page headline, e.g. "The Architect Behind the Code."
   */
  headline?: string | null;
  intro?: LexicalRichText<LexicalNodes_F1434086> | null;
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OriginStoryBlock".
 */
export interface OriginStoryBlock {
  heading?: string | null;
  content?: LexicalRichText<LexicalNodes_F1434086> | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'originStory';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhilosophyBlock".
 */
export interface PhilosophyBlock {
  heading?: string | null;
  intro?: LexicalRichText<LexicalNodes_F1434086> | null;
  values?:
    | {
        /**
         * Icon name, e.g. "Shield".
         */
        icon?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'philosophy';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  heading?: string | null;
  items?:
    | {
        year?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillsBlock".
 */
export interface SkillsBlock {
  heading?: string | null;
  categories?:
    | {
        name?: string | null;
        tools?: string | null;
        context?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'skills';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BeyondCodeBlock".
 */
export interface BeyondCodeBlock {
  heading?: string | null;
  /**
   * Short personal paragraphs — interests, hobbies, the human side.
   */
  paragraphs?:
    | {
        paragraph?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'beyondCode';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CertificationsBlock".
 */
export interface CertificationsBlock {
  heading?: string | null;
  items?:
    | {
        name?: string | null;
        issuer?: string | null;
        year?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'certifications';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  layout?:
    | (
        | HeroBlock
        | PainPointsBlock
        | MiniStackBlock
        | AboutBlock
        | WorksBlock
        | ServicesBlock
        | IndustriesBlock
        | ProcessBlock
        | TestimonialsBlock
        | InsightsBlock
        | PageCTABlock
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PainPointsBlock".
 */
export interface PainPointsBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'painPoints';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MiniStackBlock".
 */
export interface MiniStackBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'miniStack';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorksBlock".
 */
export interface WorksBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'works';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustriesBlock".
 */
export interface IndustriesBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'industries';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock".
 */
export interface ProcessBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'process';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightsBlock".
 */
export interface InsightsBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'insights';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageCTABlock".
 */
export interface PageCTABlock {
  title?: string | null;
  subtitle?: string | null;
  primaryLabel?: string | null;
  primaryTo?: string | null;
  secondaryLabel?: string | null;
  secondaryTo?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume".
 */
export interface Resume {
  id: number;
  name: string;
  /**
   * Role line shown under the name, e.g. "Full-Stack Developer & AI Architect".
   */
  title?: string | null;
  email?: string | null;
  phone?: string | null;
  location?: string | null;
  website?: string | null;
  linkedin?: string | null;
  github?: string | null;
  /**
   * Display version, e.g. "v2025.08".
   */
  version?: string | null;
  highlights?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  summary?: LexicalRichText<LexicalNodes_F30819D6> | null;
  experience?:
    | {
        role?: string | null;
        company?: string | null;
        period?: string | null;
        location?: string | null;
        summary?: string | null;
        achievements?:
          | {
              achievement?: string | null;
              id?: string | null;
            }[]
          | null;
        stack?:
          | {
              tech?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        degree?: string | null;
        institution?: string | null;
        period?: string | null;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        category?: string | null;
        items?:
          | {
              item?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        name?: string | null;
        issuer?: string | null;
        year?: string | null;
        id?: string | null;
      }[]
    | null;
  speaking?:
    | {
        event?: string | null;
        title?: string | null;
        year?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uses".
 */
export interface Use {
  id: number;
  intro?: LexicalRichText<LexicalNodes_F30819D6> | null;
  sections?:
    | {
        title?: string | null;
        subtitle?: string | null;
        items?:
          | {
              name?: string | null;
              detail?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "now".
 */
export interface Now {
  id: number;
  /**
   * Display label, e.g. "AUGUST_2026".
   */
  updated?: string | null;
  intro?: LexicalRichText<LexicalNodes_F30819D6> | null;
  blocks?:
    | {
        /**
         * Mono label, e.g. "CURRENTLY_BUILDING".
         */
        label?: string | null;
        title?: string | null;
        items?:
          | {
              name?: string | null;
              detail?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speaking".
 */
export interface Speaking {
  id: number;
  intro?: LexicalRichText<LexicalNodes_F1434086> | null;
  /**
   * Past and upcoming talks, panels and workshops.
   */
  talks?:
    | {
        title: string;
        event?: string | null;
        /**
         * e.g. "2026" or "Mar 2026".
         */
        year?: string | null;
        location?: string | null;
        /**
         * Optional link to the talk, recording or slides.
         */
        link?: string | null;
        description?: string | null;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  name?: T;
  roles?:
    | T
    | {
        role?: T;
        id?: T;
      };
  tagline?: T;
  availability?: T;
  location?: T;
  email?: T;
  calendlyUrl?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  heroHeadline?: T;
  heroIntro?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  clients?:
    | T
    | {
        name?: T;
        type?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        subtitle?: T;
        primaryLabel?: T;
        primaryTo?: T;
        secondaryLabel?: T;
        secondaryTo?: T;
      };
  contactIntro?: T;
  contactChannels?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  projectTypes?:
    | T
    | {
        type?: T;
        id?: T;
      };
  budgetRanges?:
    | T
    | {
        range?: T;
        id?: T;
      };
  timelines?:
    | T
    | {
        timeline?: T;
        id?: T;
      };
  contactSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  contactFaq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  footerNote?: T;
  footerLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        aboutHero?: T | AboutHeroBlockSelect<T>;
        originStory?: T | OriginStoryBlockSelect<T>;
        philosophy?: T | PhilosophyBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        skills?: T | SkillsBlockSelect<T>;
        beyondCode?: T | BeyondCodeBlockSelect<T>;
        certifications?: T | CertificationsBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHeroBlock_select".
 */
export interface AboutHeroBlockSelect<T extends boolean = true> {
  portrait?: T;
  headline?: T;
  intro?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OriginStoryBlock_select".
 */
export interface OriginStoryBlockSelect<T extends boolean = true> {
  heading?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhilosophyBlock_select".
 */
export interface PhilosophyBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillsBlock_select".
 */
export interface SkillsBlockSelect<T extends boolean = true> {
  heading?: T;
  categories?:
    | T
    | {
        name?: T;
        tools?: T;
        context?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BeyondCodeBlock_select".
 */
export interface BeyondCodeBlockSelect<T extends boolean = true> {
  heading?: T;
  paragraphs?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CertificationsBlock_select".
 */
export interface CertificationsBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        name?: T;
        issuer?: T;
        year?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        homeHero?: T | HeroBlockSelect<T>;
        painPoints?: T | PainPointsBlockSelect<T>;
        miniStack?: T | MiniStackBlockSelect<T>;
        about?: T | AboutBlockSelect<T>;
        works?: T | WorksBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        industries?: T | IndustriesBlockSelect<T>;
        process?: T | ProcessBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        insights?: T | InsightsBlockSelect<T>;
        pageCta?: T | PageCTABlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PainPointsBlock_select".
 */
export interface PainPointsBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MiniStackBlock_select".
 */
export interface MiniStackBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorksBlock_select".
 */
export interface WorksBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustriesBlock_select".
 */
export interface IndustriesBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock_select".
 */
export interface ProcessBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightsBlock_select".
 */
export interface InsightsBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageCTABlock_select".
 */
export interface PageCTABlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  primaryLabel?: T;
  primaryTo?: T;
  secondaryLabel?: T;
  secondaryTo?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume_select".
 */
export interface ResumeSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  email?: T;
  phone?: T;
  location?: T;
  website?: T;
  linkedin?: T;
  github?: T;
  version?: T;
  highlights?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  summary?: T;
  experience?:
    | T
    | {
        role?: T;
        company?: T;
        period?: T;
        location?: T;
        summary?: T;
        achievements?:
          | T
          | {
              achievement?: T;
              id?: T;
            };
        stack?:
          | T
          | {
              tech?: T;
              id?: T;
            };
        id?: T;
      };
  education?:
    | T
    | {
        degree?: T;
        institution?: T;
        period?: T;
        detail?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        category?: T;
        items?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        issuer?: T;
        year?: T;
        id?: T;
      };
  speaking?:
    | T
    | {
        event?: T;
        title?: T;
        year?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uses_select".
 */
export interface UsesSelect<T extends boolean = true> {
  intro?: T;
  sections?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              name?: T;
              detail?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "now_select".
 */
export interface NowSelect<T extends boolean = true> {
  updated?: T;
  intro?: T;
  blocks?:
    | T
    | {
        label?: T;
        title?: T;
        items?:
          | T
          | {
              name?: T;
              detail?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speaking_select".
 */
export interface SpeakingSelect<T extends boolean = true> {
  intro?: T;
  talks?:
    | T
    | {
        title?: T;
        event?: T;
        year?: T;
        location?: T;
        link?: T;
        description?: T;
        featured?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection:
      | 'folders'
      | 'pages'
      | 'insights'
      | 'projects'
      | 'services'
      | 'industries'
      | 'case-studies'
      | 'testimonials'
      | 'leads'
      | 'comments'
      | 'media'
      | 'categories'
      | 'users'
      | 'redirects'
      | 'forms'
      | 'form-submissions'
      | 'search';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?:
      | (
          | 'folders'
          | 'pages'
          | 'insights'
          | 'projects'
          | 'services'
          | 'industries'
          | 'case-studies'
          | 'testimonials'
          | 'leads'
          | 'comments'
          | 'media'
          | 'categories'
          | 'users'
          | 'redirects'
          | 'forms'
          | 'form-submissions'
          | 'search'
        )[]
      | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'insights';
          value: number | Insight;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'industries';
          value: number | Industry;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  id: string;
  blockType: 'banner';
  style: 'info' | 'warning' | 'error' | 'success';
  content: LexicalRichText<LexicalNodes_744BEF80>;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  id: string;
  blockType: 'code';
  language?: ('typescript' | 'javascript' | 'css' | 'python' | 'sql' | 'bash' | 'php') | null;
  code: string;
  blockName?: string | null;
}
/**
 * Multiple blocks resolve to the `MediaBlock` interface with different fields, so a content hash is appended to keep the generated types stable and unambiguous. Set a unique `interfaceName` on the block to choose the name yourself. See https://payloadcms.com/docs/typescript/generating-types#block-interface-name-collisions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_D6C44817".
 */
export interface MediaBlock_D6C44817 {
  id: string;
  blockType: 'mediaBlock';
  media: number | Media;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

/** @internal Core Lexical types — see @payloadcms/richtext-lexical. */
export type LexicalElementFormat = 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
export type LexicalElementDirection = ('ltr' | 'rtl') | null;

export interface SerializedLexicalElementBase<TChildren> {
  children: TChildren[];
  direction: LexicalElementDirection;
  format: LexicalElementFormat;
  indent: number;
  textFormat?: number;
  textStyle?: string;
  version: number;
}

export type LexicalTextMode = 'normal' | 'token' | 'segmented';

export interface SerializedTextNode {
  type: 'text';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedTabNode {
  type: 'tab';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedLineBreakNode {
  type: 'linebreak';
  version: number;
}

export interface SerializedParagraphNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'paragraph';
  textFormat: number;
  textStyle: string;
}

export interface SerializedHorizontalRuleNode {
  type: 'horizontalrule';
  version: number;
}

export interface LexicalLinkFields {
  [k: string]: unknown;
  doc?: {
    relationTo: string;
    value: Config['db']['defaultIDType'] | { [k: string]: unknown; id: Config['db']['defaultIDType'] };
  } | null;
  linkType: 'custom' | 'internal';
  newTab: boolean;
  url?: string;
}
export interface SerializedLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'link';
  fields: TFields;
  id?: string;
}
export interface SerializedAutoLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'autolink';
  fields: TFields;
}

/** Shape of a Lexical `richText` field. */
export interface LexicalRichText<TNode> {
  root: {
    children: TNode[];
    direction: LexicalElementDirection;
    format: LexicalElementFormat;
    indent: number;
    type: 'root';
    version: number;
  };
}

export interface SerializedHeadingNode<
  TChildren,
  TTag extends 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6',
> extends SerializedLexicalElementBase<TChildren> {
  type: 'heading';
  tag: TTag;
}

export interface SerializedListNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'list';
  checked?: boolean;
  listType: 'number' | 'bullet' | 'check';
  start: number;
  tag: 'ul' | 'ol';
}

export interface SerializedListItemNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'listitem';
  checked?: boolean;
  value: number;
}

export type SerializedBlockNode<TFields extends { blockType: string }> = TFields extends unknown ? {
  type: 'block';
  format: LexicalElementFormat;
  version: number;
  fields: { id: string; blockName?: string | null } & Omit<TFields, 'id' | 'blockName'>;
} : never;
export type SerializedInlineBlockNode<TFields extends { blockType: string }> = TFields extends unknown ? {
  type: 'inlineBlock';
  version: number;
  fields: { id: string } & Omit<TFields, 'id'>;
} : never;


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}